  ('Jag vill ha en egen måne', 'Ted Gärdestad', 1975, false),
  ('747', 'Kent', 1999, false),
  ('Levels - Radio Edit', 'Avicii', 2011, false),
  ('Sol, vind och vatten', 'Ted Gärdestad', 1972, true),
  ('Hooked on a Feeling', 'Blue Swede', 1974, true),
  ('SOS', 'ABBA', 1975, true),
  ('Mamma Mia', 'ABBA', 1975, true),
  ('Moviestar', 'Harpo', 1975, true),
  ('Dancing Queen', 'ABBA', 1976, true),
  ('Money, Money, Money', 'ABBA', 1976, true),
  ('Voulez-Vous', 'ABBA', 1979, true),
  ('Gimme! Gimme! Gimme! (A Man After Midnight)', 'ABBA', 1979, true),
  ('Just nu!', 'Tomas Ledin', 1980, true),
  ('Sommartider', 'Gyllene Tider', 1982, true),
  ('Öppna landskap', 'Ulf Lundell', 1982, true),
  ('Främling', 'Carola', 1983, true),
  ('Diggi-Loo Diggi-Ley', 'Herreys', 1984, true),
  ('Bra vibrationer', 'Kikki Danielsson', 1985, true),
  ('The Final Countdown', 'Europe', 1986, true),
  ('Dressed for Success', 'Roxette', 1988, true),
  ('Buffalo Stance', 'Neneh Cherry', 1988, true),
  ('The Look', 'Roxette', 1989, true),
  ('It Must Have Been Love', 'Roxette', 1990, true),
  ('Joyride', 'Roxette', 1991, true),
  ('Fading Like a Flower (Every Time You Leave)', 'Roxette', 1991, true),
  ('Fångad av en stormvind', 'Carola', 1991, true),
  ('Ängeln i rummet', 'Eva Dahlgren', 1991, true),
  ('Crucified', 'Army of Lovers', 1991, true),
  ('All That She Wants', 'Ace of Base', 1992, true),
  ('It''s My Life', 'Dr. Alban', 1992, true),
  ('How Do You Do!', 'Roxette', 1992, true),
  ('The Sign', 'Ace of Base', 1993, true),
  ('Sing Hallelujah!', 'Dr. Alban', 1993, true),
  ('Cotton Eye Joe', 'Rednex', 1994, true),
  ('Vem vet', 'Lisa Ekdahl', 1994, true),
  ('Beautiful Life', 'Ace of Base', 1995, true),
  ('Lovefool', 'The Cardigans', 1996, true),
  ('Save Tonight', 'Eagle-Eye Cherry', 1997, true),
  ('My Favourite Game', 'The Cardigans', 1998, true),
  ('Känn ingen sorg för mig Göteborg', 'Håkan Hellström', 2000, true),
  ('Hate to Say I Told You So', 'The Hives', 2000, true),
  ('It Takes a Fool to Remain Sane', 'The Ark', 2000, true),
  ('Crying at the Discoteque', 'Alcazar', 2000, true),
  ('Kom igen Lena!', 'Håkan Hellström', 2002, true),
  ('Dom andra', 'Kent', 2002, true),
  ('Utan dina andetag', 'Kent', 2002, true),
  ('Call on Me', 'Eric Prydz', 2004, true),
  ('Cry for You', 'September', 2006, true),
  ('Boten Anna', 'Basshunter', 2006, true),
  ('Release Me', 'Agnes', 2008, true),
  ('Pjanoo', 'Eric Prydz', 2008, true),
  ('Dance with Somebody', 'Mando Diao', 2009, true),
  ('Dancing on My Own', 'Robyn', 2010, true),
  ('Måndagsbarn', 'Veronica Maggio', 2011, true),
  ('Jag kommer', 'Veronica Maggio', 2011, true),
  ('Euphoria', 'Loreen', 2012, true),
  ('Don’t You Worry Child', 'Swedish House Mafia', 2012, true),
  ('I Love It', 'Icona Pop', 2012, true),
  ('Emmylou', 'First Aid Kit', 2012, true),
  ('Wake Me Up', 'Avicii', 2013, true),
  ('Hey Brother', 'Avicii', 2013, true),
  ('Habits (Stay High)', 'Tove Lo', 2013, true),
  ('Det kommer aldrig va över för mig', 'Håkan Hellström', 2013, true),
  ('Runaway (U & I)', 'Galantis', 2014, true),
  ('Waiting for Love', 'Avicii', 2015, true),
  ('Lush Life', 'Zara Larsson', 2015, true),
  ('Never Forget You', 'Zara Larsson & MNEK', 2015, true),
  ('No Money', 'Galantis', 2016, true),
  ('Square Hammer', 'Ghost', 2016, true),
  ('Without You', 'Avicii', 2017, true),
  ('SOS', 'Avicii', 2019, true)
