-- =====================================================================
--  0044  90-talspåfyllnad
-- ---------------------------------------------------------------------
--  Efter 0043 var 1990–1999 tunt (18–63 låtar/år mot 50–90 för 2000-talet).
--  TVÅ orsaker, båda åtgärdade i det här passet:
--
--   1. Rank-tröskeln 400 000 mäter DAGENS streaming. En enorm 90-talshit kan
--      ligga på 250 000 i dag, så tröskeln jämförde inte samma sak för olika
--      epoker. Sänkt till 150 000 för det här urvalet.
--
--   2. Allvarligare: årsuppskattningen som styrde 0043:s kvoter tog albumet
--      från Deezers topplåtsträff, och för äldre låtar är det ofta en
--      samlingsplatta. En 90-talslåt kunde hamna i 2005 års hink och därmed
--      aldrig ens övervägas för 90-talskvoten – helt oberoende av rank.
--      Här görs ingen förhandssortering på år alls; urvalet begränsas i
--      stället till artister som fanns i potten med låtar 1985–2001, och den
--      riktiga tvåkällsverifieringen får avgöra året.
--
--  3 271 kandidater verifierades, 1 349 fick eniga år (41 %), 490 landade
--  1990–1999 och 485 återstod efter språk- och artistkontrollen.
--
--  Samma årskrav som 0043: Deezer och MusicBrainz måste ge SAMMA år.
--  Idempotent (on conflict do nothing mot dedup-indexet). Kör efter 0043.
-- =====================================================================

insert into public.track_pool (title, artist, year, sv, genre) values
  ('It''s Not Right But It''s Okay', 'Whitney Houston', 1998, false, 'Pop'),
  ('Octobre', 'Francis Cabrel', 1994, false, 'Pop'),
  ('Around the World', 'Red Hot Chili Peppers', 1999, false, 'Alternativmusik'),
  ('Tandem', 'Vanessa Paradis', 1990, false, 'Pop'),
  ('How Do U Want It', '2Pac', 1998, false, 'Rap/Hip Hop'),
  ('Luna y sol', 'Manu Chao', 1998, false, null),
  ('Easily', 'Red Hot Chili Peppers', 1999, false, 'Alternativmusik'),
  ('Lágrimas de oro', 'Manu Chao', 1998, false, null),
  ('A Letter To Elise', 'The Cure', 1992, false, 'Alternativmusik'),
  ('Black Milk', 'Massive Attack', 1998, false, 'Electro'),
  ('Afraid to Shoot Strangers', 'Iron Maiden', 1992, false, 'Rock'),
  ('Too Young to Die', 'Jamiroquai', 1993, false, 'Pop'),
  ('Heresy', 'Nine Inch Nails', 1994, false, 'Electro'),
  ('Man Next Door', 'Massive Attack', 1998, false, 'Electro'),
  ('Dream Brother', 'Jeff Buckley', 1994, false, 'Rock'),
  ('Bodyrock', 'Moby', 1999, false, 'Pop'),
  ('Let''s Talk About Love', 'Céline Dion', 1997, false, 'Pop'),
  ('Big Me', 'Foo Fighters', 1995, false, 'Pop'),
  ('Ce matin-là', 'Air', 1998, false, 'Electro'),
  ('Mojo Pin', 'Jeff Buckley', 1994, false, 'Rock'),
  ('King for a Day', 'Jamiroquai', 1999, false, 'Pop'),
  ('Perry Mason', 'Ozzy Osbourne', 1995, false, 'Rock'),
  ('Country Boy', 'Alan Jackson', 1994, false, null),
  ('In Our Lifetime', 'Texas', 1999, false, 'Alternativmusik'),
  ('Shepherd Moons', 'Enya', 1991, false, 'Pop'),
  ('Stay', 'Sash!', 1997, false, 'Dance'),
  ('Useless', 'Depeche Mode', 1997, false, 'Pop'),
  ('Blow Your Mind', 'Jamiroquai', 1993, false, 'Pop'),
  ('I Still Believe', 'Mariah Carey', 1998, false, 'Pop'),
  ('Exchange', 'Massive Attack', 1998, false, 'Electro'),
  ('It''s A Fire', 'Portishead', 1994, false, 'Rock'),
  ('Bug A Boo', 'Destiny''s Child', 1999, false, 'Pop'),
  ('Tomorrow', 'Silverchair', 1994, false, 'Rock'),
  ('This Kiss', 'Faith Hill', 1998, false, null),
  ('10''s', 'Pantera', 1996, false, 'Pop'),
  ('Organ Donor', 'DJ Shadow', 1996, false, 'Rap/Hip Hop'),
  ('Goodnight Song', 'Tears for Fears', 1993, false, 'Pop'),
  ('We Die Young', 'Alice in Chains', 1990, false, 'Rock'),
  ('Only You', 'Portishead', 1997, false, 'Rock'),
  ('Gimme the Loot', 'The Notorious B.I.G.', 1994, false, 'Rap/Hip Hop'),
  ('Mysterious Times', 'Sash!', 1998, false, 'Dance'),
  ('Da Mystery of Chessboxin''', 'Wu-Tang Clan', 1993, false, 'Rap/Hip Hop'),
  ('Get It Together', '702', 1996, false, 'R&B'),
  ('Burnout', 'Green Day', 1994, false, 'Alternativmusik'),
  ('It''s Gotta Be You', 'Backstreet Boys', 1999, false, 'Pop'),
  ('Suicidal Thoughts', 'The Notorious B.I.G.', 1994, false, 'Rap/Hip Hop'),
  ('Unravel', 'Björk', 1997, false, 'Alternativmusik'),
  ('Biscuit', 'Portishead', 1994, false, 'Rock'),
  ('Across The Sea', 'Weezer', 1996, false, 'Rock'),
  ('Check Yo Self', 'Ice Cube', 1994, false, 'Rap/Hip Hop'),
  ('The Sidewinder Sleeps Tonite', 'R.E.M.', 1992, false, 'Alternativmusik'),
  ('Remember', 'Air', 1998, false, 'Electro'),
  ('Wu-Tang Clan Ain''t Nuthing ta F'' Wit', 'Wu-Tang Clan', 1993, false, 'Rap/Hip Hop'),
  ('Pedestal', 'Portishead', 1994, false, 'Rock'),
  ('Mindfields', 'The Prodigy', 1996, false, 'Electro'),
  ('Eternal Life', 'Jeff Buckley', 1994, false, 'Rock'),
  ('Give Me One Reason', 'Tracy Chapman', 1995, false, 'Folkmusik'),
  ('Step into a World (Rapture''s Delight)', 'KRS-One', 1997, false, 'Rap/Hip Hop'),
  ('Halftime', 'Nas', 1994, false, 'Rap/Hip Hop'),
  ('SpottieOttieDopaliscious', 'Outkast', 1998, false, 'Rap/Hip Hop'),
  ('Everyday Struggle', 'The Notorious B.I.G.', 1994, false, 'Rap/Hip Hop'),
  ('Shame On a Nigga', 'Wu-Tang Clan', 1993, false, 'Rap/Hip Hop'),
  ('Until I Drown', 'Tears for Fears', 1995, false, 'Rock'),
  ('Vietnow', 'Rage Against the Machine', 1996, false, 'Rock'),
  ('Corpus Christi Carol', 'Jeff Buckley', 1994, false, 'Rock'),
  ('Pink Triangle', 'Weezer', 1996, false, 'Rock'),
  ('Then The Morning Comes', 'Smash Mouth', 1999, false, 'Rock'),
  ('It Ain''t Hard to Tell', 'Nas', 1994, false, 'Rap/Hip Hop'),
  ('Half A World Away', 'R.E.M.', 1991, false, 'Alternativmusik'),
  ('Rags To Rags', 'Eels', 1996, false, 'Rock'),
  ('Born of a Broken Man', 'Rage Against the Machine', 1999, false, 'Rock'),
  ('I Need You Tonight', 'Backstreet Boys', 1999, false, 'Pop'),
  ('Buggin'' Out', 'A Tribe Called Quest', 1991, false, 'Rap/Hip Hop'),
  ('Kids Of The K-Hole', 'NOFX', 1997, false, 'Alternativmusik'),
  ('Suave', 'Elvis Crespo', 1999, false, 'Latinomusik'),
  ('So Good', 'Destiny''s Child', 1999, false, 'Pop'),
  ('Isobel', 'Björk', 1995, false, 'Alternativmusik'),
  ('You''ll Be Mine (Party Time)', 'Gloria Estefan', 1996, false, 'Pop'),
  ('Crying', 'Björk', 1993, false, 'Alternativmusik'),
  ('Don''t Wanna Lose You Now', 'Backstreet Boys', 1999, false, 'Pop'),
  ('Cut-Throat', 'Sepultura', 1996, false, 'Metal'),
  ('Scene Seven: I. The Dance of Eternity', 'Dream Theater', 1999, false, 'Metal'),
  ('Undenied', 'Portishead', 1997, false, 'Rock'),
  ('Desperate Cry', 'Sepultura', 1991, false, 'Rock'),
  ('A Certain Shade of Green', 'Incubus', 1997, false, 'Alternativmusik'),
  ('Pink', 'Aerosmith', 1997, false, 'Rock'),
  ('Love Oh Love', 'Lionel Richie', 1992, false, 'Pop'),
  ('Twilight Zone', '2 Unlimited', 1992, false, 'Dance'),
  ('Psycho Holiday', 'Pantera', 1990, false, 'Rock'),
  ('La sirena varada', 'Héroes del Silencio', 1993, false, 'Pop'),
  ('Lifted', 'Lighthouse Family', 1996, false, 'Pop'),
  ('When Doves Cry', 'Ginuwine', 1996, false, 'Pop'),
  ('Vitamin', 'Incubus', 1997, false, 'Alternativmusik'),
  ('The Wind', 'PJ Harvey', 1998, false, 'Rock'),
  ('It''s Not Easy', 'Lucky Dube', 1992, false, 'Reggae'),
  ('Steelo', '702', 1996, false, 'R&B'),
  ('Summer Romance (Anti-Gravity Love Song)', 'Incubus', 1997, false, 'Alternativmusik'),
  ('She''s My Baby', 'Mazzy Star', 1993, false, 'Rock'),
  ('Favola', 'Eros Ramazzotti', 1993, false, 'Pop'),
  ('Out Of Control', 'The Chemical Brothers', 1999, false, 'Dance'),
  ('Revolver', 'Rage Against the Machine', 1996, false, 'Rock'),
  ('Affirmation', 'Savage Garden', 1999, false, 'Pop'),
  ('Privilege', 'Incubus', 1999, false, 'Alternativmusik'),
  ('Come See Me', 'Soul for Real', 1999, false, 'Rap/Hip Hop'),
  ('Miss You Love', 'Silverchair', 1999, false, 'Alternativmusik'),
  ('Da Ya Think I''m Sexy?', 'N-Trance', 1997, false, 'Dance'),
  ('Anywhere', '112', 1998, false, 'R&B'),
  ('Not If You Were The Last Junkie On Earth', 'The Dandy Warhols', 1997, false, 'Alternativmusik'),
  ('The Dancer', 'PJ Harvey', 1995, false, 'Rock'),
  ('One More Road To Cross', 'DMX', 1999, false, 'Rap/Hip Hop'),
  ('Regular People (Conceit)', 'Pantera', 1992, false, 'Rock'),
  ('4 Page Letter', 'Aaliyah', 1996, false, 'R&B'),
  ('Roses', 'Silverchair', 1996, false, 'Rock'),
  ('Don''t Look Any Further', 'M People', 1993, false, 'Pop'),
  ('Steve Biko (Stir It Up)', 'A Tribe Called Quest', 1993, false, 'Rap/Hip Hop'),
  ('Cemetery', 'Silverchair', 1996, false, 'Rock'),
  ('Suite from Forrest Gump', 'Alan Silvestri', 1994, false, 'Film/Videospel'),
  ('Abuse Me', 'Silverchair', 1996, false, 'Rock'),
  ('Awful', 'Hole', 1998, false, 'Rock'),
  ('Crackerman', 'Stone Temple Pilots', 1992, false, 'Pop'),
  ('James Bond Theme', 'The Skatalites', 1997, false, 'Rock'),
  ('Northern Star', 'Hole', 1998, false, 'Rock'),
  ('Sending My Love', 'Zhané', 1994, false, 'R&B'),
  ('Rebel In Disguise', 'Ziggy Marley & The Melody Makers', 1993, false, 'Reggae'),
  ('Back & Forth', 'Aaliyah', 1994, false, 'Rap/Hip Hop'),
  ('Tratar de Estar Mejor', 'Diego Torres', 1994, false, 'Pop'),
  ('Too Hot', 'Coolio', 1995, false, 'Rap/Hip Hop'),
  ('6, 8, 12', 'Brian McKnight', 1999, false, 'R&B'),
  ('Scene Six: Home', 'Dream Theater', 1999, false, 'Metal'),
  ('To the End', 'Blur', 1994, false, 'Rock'),
  ('Never Give Up On The Good Times', 'Spice Girls', 1997, false, 'Pop'),
  ('You Mean the World to Me', 'Toni Braxton', 1993, false, 'R&B'),
  ('The Way You Love Me', 'Faith Hill', 1999, false, 'Pop'),
  ('Let''s Ride', 'Q-Tip', 1999, false, 'Rap/Hip Hop'),
  ('Love Thing', 'Spice Girls', 1996, false, 'Pop'),
  ('Fin', 'Jaguares', 1999, false, 'Pop'),
  ('Should''ve Known Better', 'Richard Marx', 1997, false, 'Pop'),
  ('Still', 'Macy Gray', 1999, false, 'R&B'),
  ('Tell Me', 'Dru Hill', 1996, false, 'Pop'),
  ('Manteau de gloire', 'Stephan Eicher', 1993, false, 'Pop'),
  ('Meet Virginia', 'Train', 1998, false, 'Rock'),
  ('1-2-3! (Train With Me)', 'Playahitty', 1995, false, 'Dance'),
  ('Vibe', 'Zhané', 1994, false, 'R&B'),
  ('I Shot The Sheriff', 'Warren G', 1997, false, 'Rap/Hip Hop'),
  ('I''ll Be Around', 'Rappin'' 4-Tay', 1994, false, 'Rap/Hip Hop'),
  ('Metal Warriors', 'Manowar', 1992, false, 'Rock'),
  ('Diggin'' On You', 'TLC', 1994, false, 'R&B'),
  ('No Time To Play', 'Guru', 1993, false, 'Rap/Hip Hop'),
  ('Love Sees No Colour', 'U96', 1993, false, 'Electro'),
  ('One Too Many Mornings', 'The Chemical Brothers', 1995, false, 'Electro'),
  ('Scene Five: Through Her Eyes', 'Dream Theater', 1999, false, 'Metal'),
  ('I Can''t Stand The Rain', 'The Commitments', 1991, false, 'Pop'),
  ('Angola', 'Cesária Evora', 1992, false, 'Dance'),
  ('Feel The Music', 'Guru', 1995, false, 'Rap/Hip Hop'),
  ('Something''s Got A Hold On Me', 'Vaya Con Dios', 1996, false, 'Alternativmusik'),
  ('Wasted', 'Mazzy Star', 1993, false, 'Rock'),
  ('Little Girl', 'H-Blockx', 1994, false, 'Pop'),
  ('Do You Love Me Now?', 'The Breeders', 1992, false, 'Alternativmusik'),
  ('The Fun Lovin'' Criminal', 'Fun Lovin'' Criminals', 1996, false, 'Rap/Hip Hop'),
  ('Disappear', 'Mazzy Star', 1996, false, 'Rock'),
  ('The Animal Song', 'Savage Garden', 1999, false, 'Pop'),
  ('Thirteen', 'Danzig', 1999, false, 'Rock'),
  ('Dyin'' Ain''t Much Of A Livin''', 'Jon Bon Jovi', 1990, false, 'Rock'),
  ('Vocab', 'Fugees', 1994, false, 'R&B'),
  ('Explode', 'The Cardigans', 1998, false, 'Pop'),
  ('Remember The Time', 'Nana', 1998, false, 'Rap/Hip Hop'),
  ('Kindergarten', 'Faith No More', 1992, false, 'Pop'),
  ('Unreflected', 'Mazzy Star', 1993, false, 'Rock'),
  ('Two Beds And A Coffee Machine', 'Savage Garden', 1999, false, 'Pop'),
  ('Why I Love You So Much', 'Monica', 1995, false, 'R&B'),
  ('I Love You Mary Jane', 'Sonic Youth', 1993, false, 'Rock'),
  ('Southernplayalisticadillacmuzik', 'Outkast', 1994, false, 'Rap/Hip Hop'),
  ('Have A Good Time', 'The Brand New Heavies', 1994, false, 'R&B'),
  ('Eins Zwei', 'Mo-Do', 1994, false, 'Electro'),
  ('Mista Mista', 'Fugees', 1996, false, 'Rap/Hip Hop'),
  ('Take A Look (At Yourself)', 'Guru', 1993, false, 'Rap/Hip Hop'),
  ('Race for the Prize', 'The Flaming Lips', 1999, false, 'Alternativmusik'),
  ('Heaven Stood Still', 'Willy DeVille', 1993, false, 'Rock'),
  ('Big Bang Baby', 'Stone Temple Pilots', 1996, false, 'Alternativmusik'),
  ('Who Was In My Room Last Night?', 'Butthole Surfers', 1993, false, 'Rock'),
  ('Electronic Pleasure', 'N-Trance', 1995, false, 'Dance'),
  ('Summer Rain', 'Belinda Carlisle', 1990, false, 'Pop'),
  ('Thunder', 'East 17', 1995, false, 'Pop'),
  ('London Loves', 'Blur', 1994, false, 'Rock'),
  ('Are You Ready To Fly', 'Rozalla', 1992, false, 'Electro'),
  ('Take Me To The River', 'The Commitments', 1991, false, 'Pop'),
  ('Something Kinda Funny', 'Spice Girls', 1996, false, 'Pop'),
  ('Tú Y Yo', 'Paulina Rubio', 1996, false, 'Pop'),
  ('Rhymes Of An Hour', 'Mazzy Star', 1996, false, 'Rock'),
  ('Supernova Goes Pop', 'Powerman 5000', 1999, false, 'Rock'),
  ('Harry & Grace Make Peace', 'Trevor Rabin', 1998, false, 'Film/Videospel'),
  ('Dying', 'Hole', 1998, false, 'Rock'),
  ('La espuma de Venus', 'Héroes del Silencio', 1995, false, 'Pop'),
  ('4 Seasons Of Loneliness', 'Boyz II Men', 1997, false, 'Pop'),
  ('Are You Ready To Fly', 'Dune', 1995, false, 'Electro'),
  ('Sweet Surrender', 'Sarah McLachlan', 1997, false, 'Pop'),
  ('Release Me', 'Wilson Phillips', 1990, false, 'Pop'),
  ('War', 'Joe Satriani', 1992, false, 'Rock'),
  ('Dreams', 'Nana', 1998, false, 'Rap/Hip Hop'),
  ('Naked', 'Spice Girls', 1996, false, 'Pop'),
  ('In The Midnight Hour', 'The Commitments', 1991, false, 'Pop'),
  ('Oración', 'Héroes del Silencio', 1990, false, 'Latinomusik'),
  ('Shimmer', 'Fuel', 1996, false, 'Rock'),
  ('La Novela', 'Fulanito', 1997, false, 'Latinomusik'),
  ('No Surrender', 'Bone Thugs-N-Harmony', 1994, false, 'Rap/Hip Hop'),
  ('Soulshine', 'The Allman Brothers Band', 1995, false, 'Pop'),
  ('Good Morning', 'The Dandy Warhols', 1997, false, 'Alternativmusik'),
  ('The Sunshine Underground', 'The Chemical Brothers', 1999, false, 'Dance'),
  ('The Changingman', 'Paul Weller', 1995, false, 'Rock'),
  ('I Saw Red', 'Warrant', 1990, false, 'Rock'),
  ('Where The River Flows', 'Collective Soul', 1995, false, 'Rock'),
  ('Never', 'Boyz II Men', 1997, false, 'Pop'),
  ('Speed Law', 'Mos Def', 1999, false, 'Pop'),
  ('Hold Me', 'Savage Garden', 1999, false, 'Pop'),
  ('Always On My Mind', 'Chris de Burgh', 1995, false, 'Rock'),
  ('The Universal', 'Blur', 1995, false, 'Rock'),
  ('No Tears To Cry', 'Whigfield', 1997, false, 'Dance'),
  ('La herida', 'Héroes del Silencio', 1993, false, 'Pop'),
  ('(Lay Your Head On My) Pillow', 'Tony! Toni! Toné!', 1993, false, 'R&B'),
  ('Big Mistake', 'Natalie Imbruglia', 1997, false, 'Pop'),
  ('Transit Ride', 'Guru', 1993, false, 'Rap/Hip Hop'),
  ('Use Your Heart', 'SWV', 1996, false, 'R&B'),
  ('Every Baby', 'The Kelly Family', 1996, false, 'Pop'),
  ('Last Time Lover', 'Spice Girls', 1996, false, 'Pop'),
  ('You Wanted More', 'Tonic', 1999, false, 'Rock'),
  ('Can''t Truss It', 'Public Enemy', 1991, false, 'Rap/Hip Hop'),
  ('If U Can''t Dance', 'Spice Girls', 1996, false, 'Pop'),
  ('The Dark End Of The Street', 'The Commitments', 1991, false, 'Pop'),
  ('Post Houmous', 'Morcheeba', 1996, false, 'Pop'),
  ('Down The Backstreets', 'Guru', 1993, false, 'Rap/Hip Hop'),
  ('Two Dope Boyz (In a Cadillac)', 'Outkast', 1996, false, 'Rap/Hip Hop'),
  ('Ya Mama', 'The Pharcyde', 1992, false, 'Rap/Hip Hop'),
  ('The Background', 'Third Eye Blind', 1997, false, 'Alternativmusik'),
  ('Fed Up', 'House of Pain', 1996, false, 'Rap/Hip Hop'),
  ('Dear Lie', 'TLC', 1999, false, 'R&B'),
  ('Doin'' You', 'The Connells', 1993, false, 'Rock'),
  ('Baby, I Believe In You', 'New Kids on the Block', 1990, false, 'Pop'),
  ('Neither Can I', 'Slash''s Snakepit', 1995, false, 'Rock'),
  ('Jettin''', 'Digable Planets', 1994, false, 'Rap/Hip Hop'),
  ('Zero Signal', 'Fear Factory', 1995, false, 'Metal'),
  ('Black Sunshine', 'White Zombie', 1992, false, 'Rock'),
  ('Kick Your Game', 'TLC', 1994, false, 'R&B'),
  ('Rendez-Vu', 'Basement Jaxx', 1999, false, 'Electro'),
  ('Hello (Turn Your Radio On)', 'Shakespears Sister', 1992, false, 'Pop'),
  ('Lately', 'Tyrese', 1998, false, 'R&B'),
  ('Reach for the Sky', 'Firehouse', 1992, false, 'Rock'),
  ('Outta Here', 'KRS-One', 1993, false, 'Rap/Hip Hop'),
  ('Do You Believe?', 'The Beatnuts', 1997, false, 'Rap/Hip Hop'),
  ('Pacifics', 'Digable Planets', 1993, false, 'Rap/Hip Hop'),
  ('Fable', 'Robert Miles', 1996, false, 'Electro'),
  ('Super Charger Heaven', 'White Zombie', 1995, false, 'Rock'),
  ('Sega', 'Ali Farka Toure', 1994, false, null),
  ('Otha Fish', 'The Pharcyde', 1992, false, 'Rap/Hip Hop'),
  ('I''m The Only One', 'Melissa Etheridge', 1993, false, 'Pop'),
  ('Return of the "G"', 'Outkast', 1998, false, 'Rap/Hip Hop'),
  ('Clumsy', 'Our Lady Peace', 1997, false, 'Rock'),
  ('La Primavera', 'Sash!', 1998, false, 'Dance'),
  ('La Vie En Rose', 'Madeleine Peyroux', 1996, false, 'Pop'),
  ('Hand in Hand', 'Dune', 1996, false, 'Electro'),
  ('Devil Without a Cause', 'Kid Rock', 1998, false, 'Pop'),
  ('Chain Of Fools', 'The Commitments', 1991, false, 'Pop'),
  ('He''s Comin', 'Nana', 1997, false, 'Pop'),
  ('I Knew I Loved You', 'Savage Garden', 1999, false, 'Pop'),
  ('Stand by Me', 'Willy DeVille', 1993, false, 'Pop'),
  ('Nanana', 'The Kelly Family', 1996, false, 'Pop'),
  ('Graduate', 'Third Eye Blind', 1997, false, 'Alternativmusik'),
  ('Love Is The Law', 'The Seahorses', 1997, false, 'Pop'),
  ('The Promise', 'Foxy Brown', 1996, false, 'Rap/Hip Hop'),
  ('Smoke', 'Natalie Imbruglia', 1997, false, 'Pop'),
  ('Move', 'H-Blockx', 1994, false, 'Pop'),
  ('I Miss You So Much', 'TLC', 1999, false, 'R&B'),
  ('Bootie Call', 'All Saints', 1998, false, 'Pop'),
  ('I Want To Come Over', 'Melissa Etheridge', 1995, false, 'Rock'),
  ('Tell Me Do U Wanna', 'Ginuwine', 1996, false, 'R&B'),
  ('Million Miles From Home', 'Dune', 1996, false, 'Electro'),
  ('Pray', 'MC Hammer', 1990, false, 'Pop'),
  ('A Moment To Myself', 'Macy Gray', 1999, false, 'R&B'),
  ('Opio', 'Héroes del Silencio', 1995, false, 'Pop'),
  ('Destination Anywhere', 'The Commitments', 1991, false, 'Pop'),
  ('Doodah', 'Cartoons', 1998, false, 'Pop'),
  ('I Don''t Wanna Die Anymore', 'New Radicals', 1998, false, 'Rock'),
  ('Safari', 'The Breeders', 1992, false, 'Alternativmusik'),
  ('Here Come The Lords', 'Lords of the Underground', 1993, false, 'Rap/Hip Hop'),
  ('Back It Up', 'Robin S', 1993, false, 'Pop'),
  ('Boof Baf', 'Fugees', 1994, false, 'Rap/Hip Hop'),
  ('Bang A Drum', 'Jon Bon Jovi', 1990, false, 'Rock'),
  ('I Hope I Didn''t Just Give Away The Ending', 'New Radicals', 1998, false, 'Rock'),
  ('Reality', 'RMB', 1996, false, 'Dance'),
  ('Mainstream', 'Outkast', 1996, false, 'Rap/Hip Hop'),
  ('Change', 'Candlebox', 1993, false, 'Pop'),
  ('Chicken Shake', 'Stereo MC''s', 1992, false, 'Pop'),
  ('Midnight At The Oasis', 'The Brand New Heavies', 1994, false, 'R&B'),
  ('The Rose', 'LeAnn Rimes', 1997, false, null),
  ('Because It''s Love', 'The Kelly Family', 1997, false, 'Pop'),
  ('You Don''t Know', '702', 1999, false, 'R&B'),
  ('Don''t Stop (Wiggle Wiggle)', 'The Outhere Brothers', 1994, false, 'Dance'),
  ('Picture Postcards From L.A.', 'Joshua Kadison', 1993, false, 'Pop'),
  ('Flown Away', 'Lene Marlin', 1999, false, 'Pop'),
  ('Moving Through Time', 'Angelo Badalamenti', 1992, false, 'Film/Videospel'),
  ('I''m A Swing It', 'House of Pain', 1994, false, 'Alternativmusik')
on conflict do nothing;

insert into public.track_pool (title, artist, year, sv, genre) values
  ('Love''s Train', 'Dru Hill', 1996, false, 'Pop'),
  ('If I Had No Loot', 'Tony! Toni! Toné!', 1993, false, 'R&B'),
  ('A Friend', 'KRS-One', 1997, false, 'Rap/Hip Hop'),
  ('Let It Rain', 'Nana', 1997, false, 'Pop'),
  ('Saint Joe On The School Bus', 'Marcy Playground', 1997, false, 'Rock'),
  ('Darkman', 'Nana', 1996, false, 'Pop'),
  ('Bad Blood', 'Ministry', 1999, false, 'Alternativmusik'),
  ('Bob''s Yer Uncle', 'Happy Mondays', 1990, false, 'Alternativmusik'),
  ('Rain', 'SWV', 1997, false, 'R&B'),
  ('Find Another Way', 'Captain Hollywood Project', 1995, false, 'Dance'),
  ('I''m That Type Of Nigga', 'The Pharcyde', 1992, false, 'Rap/Hip Hop'),
  ('Dad', 'K''s Choice', 1995, false, 'Pop'),
  ('Never Make A Promise', 'Dru Hill', 1996, false, 'Pop'),
  ('Don''t Cry Dry Your Eyes', 'Fugees', 1996, false, 'Rap/Hip Hop'),
  ('Dream On Dreamer', 'The Brand New Heavies', 1994, false, 'R&B'),
  ('Dog It', 'Digable Planets', 1994, false, 'Rap/Hip Hop'),
  ('God of Wine', 'Third Eye Blind', 1997, false, 'Alternativmusik'),
  ('We Have All the Time in the World', 'Fun Lovin'' Criminals', 1996, false, 'Rap/Hip Hop'),
  ('Deliverance', 'The Mission', 1994, false, 'Rock'),
  ('Butterflies Instead', 'K''s Choice', 1998, false, 'Alternativmusik'),
  ('Be My Baby Tonight', 'John Michael Montgomery', 1994, false, null),
  ('Punk It Up', 'Infectious Grooves', 1991, false, 'Rock'),
  ('Blind Faith', 'Warrant', 1990, false, 'Rock'),
  ('Is This Me?', 'Coolio', 1995, false, 'Rap/Hip Hop'),
  ('Borough Check', 'Digable Planets', 1994, false, 'Rap/Hip Hop'),
  ('Slowes'' Comb / The May 4th Movement Starring Doodlebug', 'Digable Planets', 1994, false, 'Rap/Hip Hop'),
  ('Gotta Stay High', 'New Radicals', 1998, false, 'Rock'),
  ('C''mon N'' Ride It (The Train)', 'Quad City DJ''s', 1996, false, 'Dance'),
  ('I Will Follow You', 'Modern Talking', 1998, false, 'Pop'),
  ('Never Gonna Say I''m Sorry', 'Ace of Base', 1995, false, 'Pop'),
  ('Cruisin''', 'Coolio', 1995, false, 'Rap/Hip Hop'),
  ('Black Ego', 'Digable Planets', 1994, false, 'Rap/Hip Hop'),
  ('Dime Jaguar', 'Jaguares', 1996, false, 'Pop'),
  ('Playing My Game', 'Lene Marlin', 1999, false, 'Pop'),
  ('You''re Always On My Mind', 'SWV', 1992, false, 'R&B'),
  ('Jesse James', 'Scarface', 1994, false, 'Rap/Hip Hop'),
  ('Vergammelte Speisen', 'Die Prinzen', 1992, false, 'Pop'),
  ('Esta luz nunca se apagará', 'Mikel Erentxun', 1992, false, 'Pop'),
  ('Baby Keep Smiling', 'Lou Bega', 1999, false, 'Dance'),
  ('Dime Store Rock', 'Slash''s Snakepit', 1995, false, 'Rock'),
  ('Here Comes My Baby', 'The Mavericks', 1999, false, 'Pop'),
  ('Mr. Rainmaker', 'Warrant', 1990, false, 'Rock'),
  ('Narcolepsy', 'Third Eye Blind', 1997, false, 'Alternativmusik'),
  ('For A Reason', 'Zhané', 1994, false, 'R&B'),
  ('It Matters to Me', 'Faith Hill', 1995, false, null),
  ('(Can''t You) Trip Like I Do', 'Filter', 1999, false, 'Alternativmusik'),
  ('Ground Level', 'Stereo MC''s', 1992, false, 'Pop'),
  ('Take Me to the Limit', 'Mr. President', 1997, false, 'Pop'),
  ('One Year Ago', 'Lene Marlin', 1999, false, 'Pop'),
  ('No One''s', 'Foxy Brown', 1996, false, 'Rap/Hip Hop'),
  ('Montage from Twin Peaks', 'Angelo Badalamenti', 1992, false, 'Film/Videospel'),
  ('Foolish Heart', 'The Mavericks', 1995, false, 'Pop'),
  ('Las Ratas No Tienen Alas', 'Jaguares', 1996, false, 'Pop'),
  ('24/7', '3T', 1995, false, 'R&B'),
  ('I''ll Follow the Sun', 'Mr. President', 1995, false, 'Pop'),
  ('Boom Boom Boom', 'Infectious Grooves', 1994, false, 'Rock'),
  ('Heroin Girl', 'Everclear', 1995, false, 'Alternativmusik'),
  ('Celebrate You', 'Veruca Salt', 1994, false, 'Alternativmusik'),
  ('Rainbow To The Stars', 'Dune', 1996, false, 'Electro'),
  ('Quiet Little Place', 'K''s Choice', 1998, false, 'Alternativmusik'),
  ('Pisschrist', 'Fear Factory', 1995, false, 'Metal'),
  ('Alone', 'Suicidal Tendencies', 1990, false, 'Rock'),
  ('Open Up Your Eyes', 'Tonic', 1996, false, 'Rock'),
  ('1+1=2', 'Lou Bega', 1999, false, 'Dance'),
  ('Until I Find You Again', 'Richard Marx', 1997, false, 'Pop'),
  ('Let''s Ride', 'Montell Jordan', 1998, false, 'R&B'),
  ('You Are My Religion', 'Firehouse', 1996, false, 'Rock'),
  ('Nobody''s Real', 'Powerman 5000', 1999, false, 'Rock'),
  ('One Second', 'Nana', 1997, false, 'Pop'),
  ('You Pick Me Up (Just To Throw Me Down)', 'Infectious Grooves', 1993, false, 'Rock'),
  ('Can''t Get Enough of Your Love', 'Taylor Dayne', 1993, false, 'Pop'),
  ('Gotta Kill Captain Stupid', 'Suicidal Tendencies', 1992, false, 'Rock'),
  ('B-Boys & Fly Girls', 'Bomfunk MC''s', 1999, false, 'Pop'),
  ('Props Over Here', 'The Beatnuts', 1994, false, 'Rap/Hip Hop'),
  ('Nunca Te Doblarás', 'Jaguares', 1996, false, 'Pop'),
  ('Waiting For The World To End', 'Rakim', 1999, false, 'R&B'),
  ('Fantasya', 'Robert Miles', 1996, false, 'Dance'),
  ('Martika''s Kitchen', 'Martika', 1991, false, 'Pop'),
  ('Ancient Walls Of Flowers', 'Marcy Playground', 1997, false, 'Rock'),
  ('Tonite', 'Phats & Small', 1999, false, 'Electro'),
  ('The White Sheet', 'Scarface', 1994, false, 'Rap/Hip Hop'),
  ('Adieu Dame Béatrice', 'Eric Lévi', 1993, false, null),
  ('Alármala de tos', 'Café Tacvba', 1996, false, 'Latinomusik'),
  ('Prettiest Eyes', 'The Beautiful South', 1994, false, 'Pop'),
  ('Sleeping With You', 'Firehouse', 1992, false, 'Rock'),
  ('D.I.S.C.O.', 'N-Trance', 1997, false, 'Pop'),
  ('Landscape', 'Robert Miles', 1996, false, 'Dance'),
  ('Smoke ''Em', 'Fun Lovin'' Criminals', 1996, false, 'Rap/Hip Hop'),
  ('4 Your Love', 'Co.Ro.', 1993, false, 'Dance'),
  ('The Magic Piper (Of Love)', 'Edwyn Collins', 1997, false, 'Alternativmusik'),
  ('Sight for Sore Eyes', 'M People', 1995, false, 'Pop'),
  ('Another Day', 'Whigfield', 1994, false, 'Dance'),
  ('Sea Of Love', 'The Mission', 1990, false, 'Pop'),
  ('Sleep on the Left Side', 'Cornershop', 1997, false, 'Alternativmusik'),
  ('Sex on the Phone', 'E-Rotic', 1995, false, 'Electro'),
  ('Maybe You''ve Been Brainwashed Too', 'New Radicals', 1998, false, 'Rock'),
  ('Addicted', 'Sisqó', 1999, false, 'R&B'),
  ('Movin'' On', 'Mýa', 1998, false, 'Pop'),
  ('I Don''t Care', 'Shakespears Sister', 1992, false, 'Rock'),
  ('Think Of Me (When You''re Lonely)', 'The Mavericks', 1999, false, 'Pop'),
  ('Slow Wine', 'Tony! Toni! Toné!', 1993, false, 'R&B'),
  ('A Reason To Believe', 'Wilson Phillips', 1990, false, 'Pop'),
  ('Let Love Speak Up Itself', 'The Beautiful South', 1990, false, 'Pop'),
  ('Don''t You', 'Candlebox', 1993, false, 'Pop'),
  ('Come Find Yourself', 'Fun Lovin'' Criminals', 1996, false, 'Rap/Hip Hop'),
  ('Huracán', 'Jaguares', 1996, false, 'Pop'),
  ('Princess of Light', 'Robert Miles', 1996, false, 'Dance'),
  ('Is Love Enough', 'Sisqó', 1999, false, 'R&B'),
  ('Future Says Run', 'Tonic', 1999, false, 'Rock'),
  ('New York State Of Mind', 'Oleta Adams', 1993, false, 'R&B'),
  ('A Cloak Of Elvenkind', 'Marcy Playground', 1997, false, 'Rock'),
  ('You Make Me Feel Like A Whore', 'Everclear', 1995, false, 'Alternativmusik'),
  ('Poppies', 'Marcy Playground', 1997, false, 'Rock'),
  ('Magic Fields', 'X-Perience', 1996, false, 'Pop'),
  ('Open Road Song', 'Eve 6', 1998, false, 'Alternativmusik'),
  ('Electric', 'Leila K', 1995, false, 'Pop'),
  ('Just For You', 'M People', 1997, false, 'Pop'),
  ('Trippin''', 'Mark Morrison', 1996, false, 'R&B'),
  ('Experience (Follow Me)', 'RMB', 1995, false, 'Electro'),
  ('I Miss You', 'Haddaway', 1993, false, 'Pop'),
  ('International Velvet', 'Catatonia', 1998, false, 'Pop'),
  ('Imagíname', 'Jaguares', 1996, false, 'Pop'),
  ('Give It Up, Turn It Loose', 'En Vogue', 1992, false, 'R&B'),
  ('Do What I Tell Ya!', 'Infectious Grooves', 1994, false, 'Rock'),
  ('So Sexual', 'Sisqó', 1999, false, 'R&B'),
  ('If You Buy This Record (Your Life Will Be Better)', 'The Tamperer', 1998, false, 'Dance'),
  ('From Da Bricks', 'Lords of the Underground', 1993, false, 'Rap/Hip Hop'),
  ('Don''t Need the Sunshine', 'Catatonia', 1998, false, 'Pop'),
  ('If You Want It', 'Soul for Real', 1995, false, 'R&B'),
  ('James Bond', 'The Skatalites', 1997, false, 'Rock'),
  ('What Would Happen', 'Meredith Brooks', 1997, false, 'Pop'),
  ('Sugar', 'Tonic', 1999, false, 'Rock'),
  ('Opium', 'Marcy Playground', 1997, false, 'Rock'),
  ('Abgehau''n', 'Die Prinzen', 1992, false, 'Pop'),
  ('Over And Over', 'Captain Hollywood Project', 1996, false, 'Dance'),
  ('Through Heaven''s Eyes', 'K-Ci & JoJo', 1998, false, 'Film/Videospel'),
  ('Blunted People', 'Demon', 1999, false, 'Electro'),
  ('Chillando Goma', 'Fulanito', 1999, false, 'Latinomusik'),
  ('Written on Ya Kitten', 'Naughty by Nature', 1993, false, 'Rap/Hip Hop'),
  ('That''s Freedom', 'John Farnham', 1990, false, 'Pop'),
  ('Living Without Your Love', 'Interactive', 1995, false, 'Electro'),
  ('Spiderman ''79', 'Veruca Salt', 1994, false, 'Alternativmusik'),
  ('Who Wants To Live Forever', 'Dune', 1996, false, 'Electro'),
  ('Too Gone, Too Long', 'En Vogue', 1997, false, 'Pop'),
  ('Rope the Moon', 'John Michael Montgomery', 1994, false, null),
  ('Impulsive', 'Wilson Phillips', 1990, false, 'Pop'),
  ('Hello Darlin', 'K-Ci & JoJo', 1999, false, 'R&B'),
  ('I Want You To Know', 'The Seahorses', 1997, false, 'Pop'),
  ('I Want To Love', 'Whigfield', 1995, false, 'Dance'),
  ('Big Time', 'Whigfield', 1995, false, 'Dance'),
  ('Forsythia', 'Veruca Salt', 1994, false, 'Alternativmusik'),
  ('Naparengas', 'Nylon Beat', 1996, false, 'Pop'),
  ('I Need You (That Thing You Do)', 'The Wonders', 1996, false, 'Film/Videospel'),
  ('Dah Dee Dah (Sexy Thing)', 'Alicia Keys', 1997, false, 'R&B'),
  ('Dirt All By My Lonely', 'Naughty by Nature', 1999, false, 'Rap/Hip Hop'),
  ('Love For Love', 'Robin S', 1993, false, 'Pop'),
  ('Don''t You Love Me Anymore', 'Bill Medley', 1991, false, null),
  ('Welcome To The Fold', 'Filter', 1999, false, 'Alternativmusik'),
  ('Say Goodbye To Babylon', 'Army of Lovers', 1991, false, 'Dance'),
  ('Over And Over', 'Wilson Phillips', 1990, false, 'Pop'),
  ('Put The Lead On Ya', 'Luniz', 1995, false, 'Rap/Hip Hop'),
  ('Next To You (Someday I''ll Be)', 'Wilson Phillips', 1990, false, 'Pop'),
  ('Super Gut', 'Mo-Do', 1994, false, 'Electro'),
  ('Pizziricco', 'The Mavericks', 1999, false, 'Pop'),
  ('Where the Sun Goes Down', 'Mr. President', 1996, false, 'Pop'),
  ('Fin de Semana', 'Los Hermanos Rosario', 1997, false, 'Latinomusik'),
  ('Goodbye Cruel World', 'Shakespears Sister', 1992, false, 'Rock'),
  ('Magaluf', 'Orup', 1992, false, 'Pop'),
  ('Love & Affection', 'Donna Lewis', 1996, false, 'Pop'),
  ('All In My Mind', 'Soul for Real', 1995, false, 'R&B'),
  ('Kein Liebeslied', 'Die Prinzen', 1993, false, 'Pop'),
  ('Changes', 'Zhané', 1994, false, 'R&B'),
  ('If Only You Knew', 'Soul for Real', 1995, false, 'R&B'),
  ('Travelling Not Running', 'EMF', 1991, false, 'Rock'),
  ('Everybody Jam!', 'Scatman John', 1996, false, 'Pop'),
  ('My Ex-Girlfriend', 'Tony! Toni! Toné!', 1993, false, 'R&B'),
  ('We Are Different', 'Members of Mayday', 1994, false, 'Electro'),
  ('The Horniest Single in the World', 'E-Rotic', 1998, false, 'Electro'),
  ('Painted Desert Serenade', 'Joshua Kadison', 1993, false, 'Pop'),
  ('Leech', 'Eve 6', 1998, false, 'Alternativmusik'),
  ('I''ll Fall In Love If You Hang Around', 'Gladys Knight', 1994, false, 'R&B'),
  ('Agenais', 'Donna Lewis', 1996, false, 'Pop'),
  ('Off My Mind', 'Zhané', 1994, false, 'R&B'),
  ('4 on the Floor', 'Mr. President', 1995, false, 'Pop'),
  ('Popstar', 'Scatman John', 1995, false, 'Pop')
on conflict do nothing;

notify pgrst, 'reload schema';
