-- ====================================================================
--  0046  Genre på de svenska låtarna
-- --------------------------------------------------------------------
--  De 250 svenska spåren lades in i 0025, alltså innan genre-kolumnen
--  fanns (0043). De har därför genre = NULL, och track_pool_genre_counts()
--  räknar dessutom bara icke-svenska spår. Följden: en kombination som
--  "Svenska + Pop" ger noll låtar – inte få, utan noll.
--
--  Här sätts genre på alla 250. Etiketterna är Deezers, samma vokabulär
--  som resten av potten, så _genre_key() mappar dem utan ändring.
--
--  Fördelning efter mappning till spelbara genrelägen:
--    pop                              124
--    rock                              70
--    dance                             33
--    hiphop                            11
--    (ingen – utanför genrelägena)     10
--    rnb                                2
--
--  Jazz och Folk är MEDVETET valda för visorna (Cornelis Vreeswijk, Fred
--  Åkerström, Evert Taube) och jazzen (Monica Zetterlund, Jan Johansson):
--  de mappar till NULL, så de hamnar inte i "Rock" bara för att fylla ut
--  potten. De är fortfarande med i läget "Svenska".
--
--  Raderna kommer från 0025 (250 st). Prod visar 249 svenska efter dedupen
--  i 0038, så en rad matchar sannolikt inget – ofarligt, den uppdaterar noll.
--
--  Genre är till skillnad från ÅRTAL en smaksak – en diskutabel genre kostar
--  ingen en runda, ett felaktigt årtal gör det. Därför är den här datan skriven
--  för hand, medan årtal bör hämtas från en auktoritativ källa.
--
--  Matchar på titel+artist (inte id, som inte är stabila mellan omkörningar).
--  Additiv + idempotent. Kör efter 0043.
-- ====================================================================

update public.track_pool tp set genre = v.genre
from (values
  ('Flottarkärlek','Snoddas','Pop'),
  ('Ann-Kristin','Snoddas','Pop'),
  ('Lilla stjärna','Alice Babs','Pop'),
  ('Är du kär i mej ännu Klas-Göran','Lill-Babs','Pop'),
  ('Tunna skivor','Owe Thörnqvist','Pop'),
  ('April, april','Lill-Babs','Pop'),
  ('Sakta vi gå genom stan','Monica Zetterlund','Jazz'),
  ('Orange Blossom Special','The Spotnicks','Rock'),
  ('Sleep Little Girl','Tages','Rock'),
  ('Cadillac','The Hep Stars','Rock'),
  ('Sunny Girl','The Hep Stars','Rock'),
  ('Wedding','The Hep Stars','Rock'),
  ('Som en dröm','Östen Warnerbring','Pop'),
  ('Här kommer natten','Pugh Rogefeldt','Rock'),
  ('Waterloo','ABBA','Pop'),
  ('SOS','ABBA','Pop'),
  ('Mamma Mia','ABBA','Pop'),
  ('Dancing Queen','ABBA','Pop'),
  ('Fernando','ABBA','Pop'),
  ('Money, Money, Money','ABBA','Pop'),
  ('Knowing Me, Knowing You','ABBA','Pop'),
  ('The Name of the Game','ABBA','Pop'),
  ('Take a Chance on Me','ABBA','Pop'),
  ('Summer Night City','ABBA','Pop'),
  ('Chiquitita','ABBA','Pop'),
  ('Voulez-Vous','ABBA','Pop'),
  ('Gimme! Gimme! Gimme! (A Man After Midnight)','ABBA','Pop'),
  ('Hooked on a Feeling','Blue Swede','Pop'),
  ('Michelangelo','Björn Skifs','Pop'),
  ('Sol, vind och vatten','Ted Gärdestad','Pop'),
  ('Jag vill ha en egen måne','Ted Gärdestad','Pop'),
  ('Come Give Me Love','Ted Gärdestad','Pop'),
  ('För kärlekens skull','Ted Gärdestad','Pop'),
  ('Satellit','Ted Gärdestad','Pop'),
  ('Vem kan man lita på','Hoola Bandoola Band','Rock'),
  ('Keops pyramid','Hoola Bandoola Band','Rock'),
  ('Speedy Gonzales','Nationalteatern','Rock'),
  ('Barn av vår tid','Nationalteatern','Rock'),
  ('Ted','Magnus Uggla','Rock'),
  ('Oh Susie','Secret Service','Pop'),
  ('Just nu!','Tomas Ledin','Pop'),
  ('Sommaren är kort','Tomas Ledin','Pop'),
  ('Flickorna på TV2','Gyllene Tider','Rock'),
  ('Ljudet av ett annat hjärta','Gyllene Tider','Rock'),
  ('Sommartider','Gyllene Tider','Rock'),
  ('Marie i växeln','Gyllene Tider','Rock'),
  ('Staten och kapitalet','Ebba Grön','Rock'),
  ('Flash in the Night','Secret Service','Pop'),
  ('Främling','Carola','Pop'),
  ('Diggi-Loo Diggi-Ley','Herreys','Pop'),
  ('One Night in Bangkok','Murray Head','Pop'),
  ('I Know Him So Well','Elaine Paige & Barbara Dickson','Pop'),
  ('Bra vibrationer','Kikki Danielsson','Pop'),
  ('2000 eldar','Imperiet','Rock'),
  ('The Final Countdown','Europe','Rock'),
  ('Carrie','Europe','Rock'),
  ('Rock the Night','Europe','Rock'),
  ('Kung för en dag','Magnus Uggla','Pop'),
  ('Superstitious','Europe','Rock'),
  ('Dressed for Success','Roxette','Pop'),
  ('Listen to Your Heart','Roxette','Pop'),
  ('Stad i ljus','Tommy Körberg','Pop'),
  ('The Look','Roxette','Pop'),
  ('It Must Have Been Love','Roxette','Pop'),
  ('Dangerous','Roxette','Pop'),
  ('Joyride','Roxette','Pop'),
  ('Fading Like a Flower (Every Time You Leave)','Roxette','Pop'),
  ('Fångad av en stormvind','Carola','Pop'),
  ('Ängeln i rummet','Eva Dahlgren','Pop'),
  ('All That She Wants','Ace of Base','Pop'),
  ('Himlen runt hörnet','Lisa Nilsson','Pop'),
  ('It''s My Life','Dr. Alban','Dance'),
  ('How Do You Do!','Roxette','Pop'),
  ('Here We Go','Stakka Bo','Pop'),
  ('The Sign','Ace of Base','Pop'),
  ('Happy Nation','Ace of Base','Pop'),
  ('Sing Hallelujah!','Dr. Alban','Dance'),
  ('Cotton Eye Joe','Rednex','Dance'),
  ('Vandraren','Nordman','Pop'),
  ('Set the World on Fire','E-Type','Dance'),
  ('This Is the Way','E-Type','Dance'),
  ('Beautiful Life','Ace of Base','Pop'),
  ('Carnival','The Cardigans','Pop'),
  ('Kräm (så nära får ingen gå)','Kent','Rock'),
  ('747','Kent','Rock'),
  ('Lovefool','The Cardigans','Pop'),
  ('Here I Go Again','E-Type','Dance'),
  ('Show Me Love','Robyn','Pop'),
  ('Do You Know (What It Takes)','Robyn','Pop'),
  ('Om du var här','Kent','Rock'),
  ('Save Tonight','Eagle-Eye Cherry','Rock'),
  ('My Favourite Game','The Cardigans','Alternativmusik'),
  ('Erase/Rewind','The Cardigans','Alternativmusik'),
  ('Mikrofonkåt','Petter','Rap/Hip Hop'),
  ('Musik non stop','Kent','Rock'),
  ('Take Me to Your Heaven','Charlotte Nilsson','Pop'),
  ('Mamma Mia','A-Teens','Pop'),
  ('Känn ingen sorg för mig Göteborg','Håkan Hellström','Rock'),
  ('Hate to Say I Told You So','The Hives','Rock'),
  ('Main Offender','The Hives','Rock'),
  ('It Takes a Fool to Remain Sane','The Ark','Rock'),
  ('Crying at the Discoteque','Alcazar','Dance'),
  ('Popular','Darin','Pop'),
  ('Kom igen Lena!','Håkan Hellström','Rock'),
  ('Dom andra','Kent','Rock'),
  ('Max 500','Kent','Rock'),
  ('Sundance Kid','Kent','Rock'),
  ('Call on Me','Eric Prydz','Dance'),
  ('Walk Idiot Walk','The Hives','Rock'),
  ('Calleth You, Cometh I','The Ark','Rock'),
  ('Palace & Main','Kent','Rock'),
  ('Vinternoll2','Kent','Rock'),
  ('Alla vill till himmelen','Timbuktu','Rap/Hip Hop'),
  ('Sunshine in the Rain','BWO','Dance'),
  ('Cry for You','September','Dance'),
  ('Boten Anna','Basshunter','Dance'),
  ('With Every Heartbeat','Robyn','Dance'),
  ('Now You’re Gone','Basshunter','Dance'),
  ('Cara Mia','Måns Zelmerlöw','Pop'),
  ('Om du lämnade mig nu','Lars Winnerbäck & Miss Li','Pop'),
  ('Tick Tick Boom','The Hives','Rock'),
  ('Release Me','Agnes','Pop'),
  ('Pjanoo','Eric Prydz','Dance'),
  ('Dance with Somebody','Mando Diao','Rock'),
  ('Dancing on My Own','Robyn','Pop'),
  ('One','Swedish House Mafia','Dance'),
  ('2 steg från Paradise','Håkan Hellström','Rock'),
  ('Måndagsbarn','Veronica Maggio','Pop'),
  ('Jag kommer','Veronica Maggio','Pop'),
  ('Levels','Avicii','Dance'),
  ('Save the World','Swedish House Mafia','Dance'),
  ('Popular','Eric Saade','Pop'),
  ('Euphoria','Loreen','Pop'),
  ('Don’t You Worry Child','Swedish House Mafia','Dance'),
  ('I Love It','Icona Pop','Dance'),
  ('Emmylou','First Aid Kit','Folk'),
  ('I Follow Rivers','Lykke Li','Pop'),
  ('Million Voices','Otto Knows','Dance'),
  ('Wake Me Up','Avicii','Dance'),
  ('Hey Brother','Avicii','Dance'),
  ('Uncover','Zara Larsson','Pop'),
  ('Habits (Stay High)','Tove Lo','Pop'),
  ('Hela huset','Veronica Maggio','Pop'),
  ('Sergels torg','Veronica Maggio','Pop'),
  ('Valborg','Håkan Hellström','Rock'),
  ('Finders Keepers','Miriam Bryant','Pop'),
  ('The Nights','Avicii','Dance'),
  ('Runaway (U & I)','Galantis','Dance'),
  ('Heroes (We Could Be)','Alesso','Dance'),
  ('My Silver Lining','First Aid Kit','Folk'),
  ('Talking Body','Tove Lo','Pop'),
  ('Undo','Sanna Nielsen','Pop'),
  ('Younger','Seinabo Sey','R&B'),
  ('Waiting for Love','Avicii','Dance'),
  ('Lush Life','Zara Larsson','Pop'),
  ('Never Forget You','Zara Larsson & MNEK','Pop'),
  ('Heroes','Måns Zelmerlöw','Pop'),
  ('If I Were Sorry','Frans','Pop'),
  ('No Money','Galantis','Dance'),
  ('Cool Girl','Tove Lo','Pop'),
  ('Symphony','Clean Bandit & Zara Larsson','Dance'),
  ('Without You','Avicii','Dance'),
  ('I Can’t Go On','Robin Bengtsson','Pop'),
  ('Dance You Off','Benjamin Ingrosso','Pop'),
  ('Too Late for Love','John Lundvik','Pop'),
  ('Katten i trakten','Einár','Rap/Hip Hop'),
  ('SOS','Avicii','Dance'),
  ('Svag','Victor Leksell','Pop'),
  ('Húsavík (My Hometown)','Molly Sandén','Pop'),
  ('Voices','Tusse','Pop'),
  ('Hold Me Closer','Cornelia Jakobs','Pop'),
  ('Tattoo','Loreen','Pop'),
  ('Cecilia Lind','Cornelis Vreeswijk','Folk'),
  ('Somliga går med trasiga skor','Cornelis Vreeswijk','Folk'),
  ('Jag ger dig min morgon','Fred Åkerström','Folk'),
  ('Änglamark','Evert Taube','Folk'),
  ('Sensuella Isabella','Tomas Ledin','Pop'),
  ('800°','Ebba Grön','Rock'),
  ('Die Mauer','Ebba Grön','Rock'),
  ('Öppna landskap','Ulf Lundell','Rock'),
  ('Segla på ett moln','Anne-Lie Rydé','Pop'),
  ('Ögon känsliga för ljus','Ratata','Pop'),
  ('Stockholm','Orup','Pop'),
  ('Undan för undan','Freda''','Rock'),
  ('Vem ska jag tro på?','Thomas Di Leva','Pop'),
  ('Vem tänder stjärnorna','Eva Dahlgren','Pop'),
  ('Hon är så söt','Bo Kaspers Orkester','Pop'),
  ('Vem vet','Lisa Ekdahl','Pop'),
  ('Öppna din dörr','Lisa Ekdahl','Pop'),
  ('Undantag','Bo Kaspers Orkester','Pop'),
  ('I samma bil','Bo Kaspers Orkester','Pop'),
  ('Logiskt','Petter','Rap/Hip Hop'),
  ('En midsommarnattsdröm','Håkan Hellström','Rock'),
  ('Elegi','Lars Winnerbäck','Rock'),
  ('Utan dina andetag','Kent','Rock'),
  ('Det löser sig','Timbuktu','Rap/Hip Hop'),
  ('Det gör ont','Lena Philipsson','Pop'),
  ('Las Vegas','Martin Stenmarck','Pop'),
  ('Alla vill till himlen men ingen vill dö','Thåström','Rock'),
  ('Nu kan du få mig så lätt','Håkan Hellström','Rock'),
  ('Evighet','Carola','Pop'),
  ('Ingenting','Kent','Rock'),
  ('Solregn','Lars Winnerbäck','Rock'),
  ('Kärleken kommer','Melissa Horn','Pop'),
  ('Fel del av gården','Movits!','Rap/Hip Hop'),
  ('Alla som inte dansar','Maskinen','Rap/Hip Hop'),
  ('Kärlek är för dom','Thåström','Rock'),
  ('Från och med du','Oskar Linnros','Pop'),
  ('17 år','Veronica Maggio','Pop'),
  ('Säg ingenting till mig','Melissa Horn','Pop'),
  ('Flickan och kråkan','Timbuktu','Rap/Hip Hop'),
  ('Händerna mot himlen','Petra Marklund','Pop'),
  ('För alltid','Norlie & KKV','Rap/Hip Hop'),
  ('Din soldat','Albin','Rap/Hip Hop'),
  ('Det kommer aldrig va över för mig','Håkan Hellström','Rock'),
  ('Tabanja','Cherrie','R&B'),
  ('Klär av dig','Victor Leksell','Pop'),
  ('5 minuter','Veronica Maggio','Pop'),
  ('Tänker inte alls gå hem','Miss Li','Pop'),
  ('Varm korv boogie','Owe Thörnqvist','Pop'),
  ('Augustin','Brita Borg','Pop'),
  ('Sån’t är livet','Anita Lindblom','Pop'),
  ('Jag väntar vid min mila','Hootenanny Singers','Folk'),
  ('Visa från Utanmyra','Jan Johansson','Jazz'),
  ('Kristina från Vilhelmina','Sven-Ingvars','Pop'),
  ('Leva livet','Lill-Babs','Pop'),
  ('Nygammal vals','Lill Lindfors & Svante Thuresson','Pop'),
  ('Moviestar','Harpo','Pop'),
  ('Vill ha dej','Freestyle','Pop'),
  ('En kväll i tunnelbanan','Noice','Rock'),
  ('Fyra Bugg & en Coca-Cola','Lotta Engberg','Pop'),
  ('Buffalo Stance','Neneh Cherry','Rap/Hip Hop'),
  ('Kärlekens tunga','Eldkvarn','Rock'),
  ('Crucified','Army of Lovers','Dance'),
  ('Open Sesame','Leila K','Dance'),
  ('Hobo Humpin’ Slobo Babe','Whale','Alternativmusik'),
  ('Only for the Weak','In Flames','Metal'),
  ('Alright Alright (Here’s My Fist Where’s the Fight)','Sahara Hotnights','Rock'),
  ('Living in America','The Sounds','Rock'),
  ('Hearts on Fire','HammerFall','Metal'),
  ('Jerk It Out','Caesars','Rock'),
  ('Cobrastyle','Teddybears','Alternativmusik'),
  ('This Is the World We Live In','Alcazar','Dance'),
  ('Primo Victoria','Sabaton','Metal'),
  ('Young Folks','Peter Bjorn and John','Alternativmusik'),
  ('The Lion’s Roar','First Aid Kit','Folk'),
  ('Genghis Khan','Miike Snow','Alternativmusik'),
  ('Square Hammer','Ghost','Metal'),
  ('Ciao Ciao','Klara Hammarström','Pop'),
  ('No One Dies from Love','Tove Lo','Pop')
) as v(title, artist, genre)
where tp.sv and tp.title = v.title and tp.artist = v.artist;
